import { footerAct1, footerAct2 } from '../assets/base';
import {
  sticker,
  bankBank1,
  bankBank2,
  bankBank3,
  bankBank4,
  bankBank5Pc,
  bankBank5Mb,
  bankBank6Pc,
  bankBank6Mb,
  bankBank7Pc,
  bankBank7Mb,
  mainpd1,
  mainpd2,
  mainpd3,
  mainpd4,
  subsliderHeadpic1Pc,
  subsliderHeadpic1Mb,
  subsliderHeadpic2Pc,
  subsliderHeadpic2Mb,
  subsliderPd11,
  subsliderPd12,
  subsliderPd13,
  subsliderPd14,
  subsliderPd21,
  subsliderPd22,
  subsliderPd23,
  subsliderPd24,
  theme1PdMain,
  theme1Pd1,
  theme1Pd2,
  theme1Pd3,
  theme1Pd4,
  theme1Pd5,
  theme1Pd6,
  theme1Pd7,
  theme1Pd8,
  theme2PdMain,
  theme2Pd1,
  theme2Pd2,
  theme2Pd3,
  theme2Pd4,
  theme2Pd5,
  theme2Pd6,
  theme2Pd7,
  theme2Pd8,
  theme3PdMain,
  theme3Pd1,
  theme3Pd2,
  theme3Pd3,
  theme3Pd4,
  theme3Pd5,
  theme3Pd6,
  theme3Pd7,
  theme3Pd8,
  theme4PdMain,
  theme4Pd1,
  theme4Pd2,
  theme4Pd3,
  theme4Pd4,
  theme4Pd5,
  theme4Pd6,
  theme4Pd7,
  theme4Pd8,
  themeCommonTheme1Main,
  themeCommonTheme1Pd,
} from '../assets/layout';

export const mockPdData = [
  {
    BlockId: 31,
    Nodes: [
      {
        id: 1,
        url: '',
        productName: '銀行優惠 1',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bankBank1,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '銀行優惠 2',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bankBank2,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '銀行優惠 3',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bankBank3,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '銀行優惠 4',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bankBank4,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 42,
    Nodes: [
      {
        id: 1,
        url: '',
        productName: '銀行優惠 5',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bankBank5Pc,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '銀行優惠 5',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bankBank5Mb,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '銀行優惠 6',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bankBank6Pc,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '銀行優惠 6',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bankBank6Mb,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '銀行優惠 7',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bankBank7Pc,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '銀行優惠 7',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bankBank7Mb,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 53,
    Nodes: [
      {
        id: 1,
        url: '',
        productName: '送康寧玻璃保鮮盒',
        productTitle: '高露潔 長效抗敏修護牙膏',
        marketPrice: '',
        discountPrice: '20000',
        imgSrc: mainpd1,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '2箱折150',
        productTitle: '滿意寶寶 極上呵護紙尿褲',
        marketPrice: '',
        discountPrice: '18500',
        imgSrc: mainpd2,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '滿額送育兒三好禮',
        productTitle: '小獅王辛巴 玻璃奶瓶禮盒',
        marketPrice: '',
        discountPrice: '22000',
        imgSrc: mainpd3,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '小神廚最高回饋10%',
        productTitle: 'Teamson木製兒童廚房玩具',
        marketPrice: '',
        discountPrice: '19800',
        imgSrc: mainpd4,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '小神廚最高回饋10%',
        productTitle: 'Teamson木製兒童廚房玩具',
        marketPrice: '',
        discountPrice: '21200',
        imgSrc: mainpd4,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '滿額送育兒三好禮',
        productTitle: '小獅王辛巴 玻璃奶瓶禮盒',
        marketPrice: '',
        discountPrice: '25000',
        imgSrc: mainpd3,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: '最高回饋8%P幣',
        productTitle: 'Joie tourist 自動秒收推車',
        marketPrice: '',
        discountPrice: '17900',
        imgSrc: mainpd2,
        imgTitle: '',
      },
      {
        id: 8,
        url: '',
        productName: '送康寧玻璃保鮮盒',
        productTitle: '高露潔 長效抗敏修護牙膏',
        marketPrice: '',
        discountPrice: '23400',
        imgSrc: mainpd1,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 64,
    Nodes: [
      {
        id: 1,
        url: '',
        productName: 'SubSlider Group 1 - Banner PC',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: subsliderHeadpic1Pc,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: 'SubSlider Group 1 - Banner MB',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: subsliderHeadpic1Mb,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '幫寶適 奢寵幫拉拉褲 L 32片入*3包入',
        productTitle: '呵護寶貝封漏彈力',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd11,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '幫寶適 超薄乾爽 拉拉褲(M/L)',
        productTitle: '呵護寶貝封漏彈力',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd12,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: 'pamper 一級幫 日本境內版 拉拉褲',
        productTitle: '呵護寶貝封漏彈力',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd13,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '4款尺寸任選-幫寶適極上守護',
        productTitle: '呵護寶貝封漏彈力',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd14,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 220,
    Nodes: [
      {
        id: 1,
        url: '',
        productName: 'SubSlider Group 2 - Banner PC',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: subsliderHeadpic2Pc,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: 'SubSlider Group 2 - Banner MB',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: subsliderHeadpic2Mb,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '博士倫瑞霖水漾清新多效保養液500ml',
        productTitle: '保健滿1800折200',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd21,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '博士倫舒視能單支裝舒潤液 60支入',
        productTitle: '保健滿1800折200',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd22,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '日本博士倫 藍莓葉黃素 60粒',
        productTitle: '保健滿1800折200',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd23,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '博士倫舒視能水漾平衡保養液300ml',
        productTitle: '保健滿1800折200',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd24,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 231,
    Nodes: [
      {
        id: 1,
        url: '',
        productName: 'SubSlider Group 1 - Banner PC',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: subsliderHeadpic1Pc,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: 'SubSlider Group 1 - Banner MB',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: subsliderHeadpic1Mb,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '幫寶適 奢寵幫拉拉褲 L 32片入*3包入',
        productTitle: '呵護寶貝封漏彈力',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd11,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '幫寶適 超薄乾爽 拉拉褲(M/L)',
        productTitle: '呵護寶貝封漏彈力',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd12,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: 'pamper 一級幫 日本境內版 拉拉褲',
        productTitle: '呵護寶貝封漏彈力',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd13,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '4款尺寸任選-幫寶適極上守護',
        productTitle: '呵護寶貝封漏彈力',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd14,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 242,
    Nodes: [
      {
        id: 1,
        url: '',
        productName: 'SubSlider Group 2 - Banner PC',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: subsliderHeadpic2Pc,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: 'SubSlider Group 2 - Banner MB',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: subsliderHeadpic2Mb,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '博士倫瑞霖水漾清新多效保養液500ml',
        productTitle: '保健滿1800折200',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd21,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '博士倫舒視能單支裝舒潤液 60支入',
        productTitle: '保健滿1800折200',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd22,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '日本博士倫 藍莓葉黃素 60粒',
        productTitle: '保健滿1800折200',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd23,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '博士倫舒視能水漾平衡保養液300ml',
        productTitle: '保健滿1800折200',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: subsliderPd24,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 88,
    Nodes: [
      {
        id: 1,
        url: '',
        productName: 'ARIEL 4D超濃縮抗菌洗衣球',
        productTitle: '限定微風南山店販售',
        marketPrice: '',
        discountPrice: '1280',
        imgSrc: theme1PdMain,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme1Pd1,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme1Pd2,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme1Pd3,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme1Pd4,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme1Pd5,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme1Pd6,
        imgTitle: '',
      },
      {
        id: 8,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme1Pd7,
        imgTitle: '',
      },
      {
        id: 9,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme1Pd8,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 99,
    Nodes: [
      {
        id: 1,
        url: '',
        productName: 'ARIEL 4D超濃縮抗菌洗衣球',
        productTitle: '限定微風南山店販售',
        marketPrice: '',
        discountPrice: '1280',
        imgSrc: theme2PdMain,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme2Pd1,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme2Pd2,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme2Pd3,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme2Pd4,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme2Pd5,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme2Pd6,
        imgTitle: '',
      },
      {
        id: 8,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme2Pd7,
        imgTitle: '',
      },
      {
        id: 9,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme2Pd8,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 110,
    Nodes: [
      {
        id: 1,
        url: '',
        productName: 'ARIEL 4D超濃縮抗菌洗衣球',
        productTitle: '限定微風南山店販售',
        marketPrice: '',
        discountPrice: '1280',
        imgSrc: theme3PdMain,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme3Pd1,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme3Pd2,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme3Pd3,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme3Pd4,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme3Pd5,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme3Pd6,
        imgTitle: '',
      },
      {
        id: 8,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme3Pd7,
        imgTitle: '',
      },
      {
        id: 9,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme3Pd8,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 121,
    Nodes: [
      {
        id: 1,
        url: '',
        productName: 'ARIEL 4D超濃縮抗菌洗衣球',
        productTitle: '限定微風南山店販售',
        marketPrice: '',
        discountPrice: '1280',
        imgSrc: theme4PdMain,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme4Pd1,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme4Pd2,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme4Pd3,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme4Pd4,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme4Pd5,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme4Pd6,
        imgTitle: '',
      },
      {
        id: 8,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme4Pd7,
        imgTitle: '',
      },
      {
        id: 9,
        url: '',
        productName: '麻膳堂椒麻拌麵(1袋4入)',
        productTitle: '限定微風南山店販售',
        marketPrice: '3000',
        discountPrice: '1280',
        imgSrc: theme4Pd8,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 684,
    Nodes: [
      {
        id: 2,
        url: '',
        productName: '天天簽到',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: footerAct1,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '限時瘋搶',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: footerAct2,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 772,
    Nodes: [
      {
        id: 2,
        url: '',
        productName: '活動總覽',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: sticker,
        imgTitle: '',
      },
    ],
  },
];
